services:
  auth-service:
    build: ./microservices/auth
    container_name: auth-service
    ports:
      - "50051:50051"
    networks:
      - microservices-net

  posts-service:
    build: ./microservices/posts
    container_name: posts-service
    ports:
      - "50052:50052"
    networks:
      - microservices-net

  users-service:
    build: ./microservices/users
    container_name: users-service
    ports:
      - "50053:50053"
    networks:
      - microservices-net

  envoy:
    image: envoyproxy/envoy:v1.29-latest
    # command: ["envoy", "-c", "/etc/envoy/envoy.yaml", "--log-level", "debug"]
    container_name: envoy
    depends_on:
      - auth-service
      - posts-service
      - users-service
    ports:
      - "8080:8080"
      - "9901:9901"
    volumes:
      - ./envoy/envoy.yaml:/etc/envoy/envoy.yaml
      - ./envoy/proto.pb:/etc/envoy/proto.pb
    networks:
      - microservices-net

networks:
  microservices-net:
    driver: bridge