FROM protoc-base:0.0.1

WORKDIR /app
COPY . .

#RUN mkdir /app/generated
#RUN protoc --proto_path=/opt/googleapis --proto_path=. --go_out=plugins=grpc:./generated auth.proto

# RUN apk update && apk add -y python3
RUN python3 -V
RUN python -V
